# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 937b144ef3d341db84864a930f8fc4b7f7ebcd938ed898b7e72c256a389c7898ef542d291ee1e9d7ff0a65ea17075b20df3fe3b34fdce4881dfcc3be783dca5b

test:
  secret_key_base: 503771815fab30b2ef36defe1036becaa6d63b352c318855db615e3467600c0bb544aec722667b8723ba904587e6c050e31ad12df7cb5f22bda98f7bbcb1ebea

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
